# Numpy Array

In [14]:
import numpy as np

In [15]:
# 0-D array or scalar
arr = np.array(42)
print(arr)

42


In [16]:
# 1-D array or vector
arr2 = np.array([1, 2, 3, 4, 5])
print(arr2)

[1 2 3 4 5]


In [17]:
# 2-D array or tensors
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [26]:
# 3-D array 
arr4 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr4)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
print(arr.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim) # 3 or more than 3 are 3-D arrays

0
1
2
3


In [32]:
arr5 = np.array([1, 2, 3, 4],ndmin=5)
print(arr5)
print('number of dimensions : ',arr5.ndim)

[[[1 2 3 4]]]
number of dimensions :  3


# Array Indexing

In [33]:
arr6 = np.array([1, 2, 3, 4, 5])
print(arr6[0])

1


In [34]:
arr6 = np.array([1, 2, 3, 4, 5])
print(arr6[1])

2


In [36]:
arr6 = np.array([1, 2, 3, 4, 5])
print(arr6[2]+arr6[3])

7


In [40]:
# accessing array element
arr7 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr7)
print("2nd element on first row : ", arr7[0,1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on first row :  2


In [51]:
# accessing the third element of the second array of the first array :
arr8 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr8)
print(arr8[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6
